### ISSUE TITLE
Substages compatibility issue with old json files 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#70]
If you are using old json files, the first wastewater treatment substage does not provide a the output "Total GHG Wastewater Treatment" (wwt_KPI_GHG)

![image](https://user-images.githubusercontent.com/33861734/40223927-ea0bd110-5a84-11e8-9831-681ec8203ee2.png)

See video for more details:
https://www.dropbox.com/s/dhjnwxwyzmmvqwt/Compatibility%20issue%20old%20json%20files.mp4?dl=0

See the json file used in the video here:
https://www.dropbox.com/s/ohm7jxa0tqpwa5h/Madaba%20Baseline%202016%20_Final28032018.json?dl=0

**Comment by holalluis** [comment]
Hi Ranjin, I'm answering before seeing the videos, but the reason is probably because of there is no value for "wwt_vol_tslu" which is volume of fuel used for sludge transport (which is a new input, and the old json file does not have it). If you give a value for it, it should work.

**Comment by holalluis** [comment]
ok I'll create a fix for the specific case were a variable is in the tool structure as a number but in the json file is not defined, I think this approach will fix these cases.

**Comment by holalluis** [comment]
I've implemented the fix, it should work now

**Comment by Ranf16** [comment]
I just checked and the problem still exists.

**Comment by Ranf16** [comment]
I think I can't reopen an issue. only you can.

**Comment by holalluis** [comment]
I've set that when a variable is not found inside a substages its value is zero, I tested and I think it should work, please test, and I will reopen if still not solved

**Comment by Ranf16** [comment]
The Problem is not solved. 

The total for the substage is only shown once you have activated the fitlers
-  "do you truck transport sludge to disposal site"
- "Are you producing biogas..." 
- "Are you valorizing biogas" 

see the video here:
https://www.dropbox.com/s/y3ircag9vrr0wat/Substages%20issue%20with%20old%20files.mp4?dl=0

**Comment by holalluis** [comment]
Yeah, I made a mistake that the fix only was applied to inputs which had a filter set to yes, I've corrected it to apply it to all of them, please try now
